### ISSUE TITLE
How to install the software?

### ISSUE THREAD

**Issue by mrentsch65** [fabianthome/TINF20C_Team2_ModellingWizardForCables#26]
Hallo,
es gibt leider keine User Documentation, die erklärt, wie man die Software installiert und bedient.
Vielleicht habe ich es ja übersehen, aber wo steht, was ich tun muss, um die Software bei mir lokal in Betrieb nehmen zu können?
Bitte liefern Sie das bis morgen noch nach.

**Comment by LeonAmtmann** [comment]
Guten Tag Herr Rentschler, 
die Unserdocumentation befindet sich unter PROJECT/Documentation/Userdocu.pdf

**Comment by mrentsch65** [comment]
Ja, wenn man weiss, wo die Userdoku liegt... Warum verlinken Sie die nicht über das Wiki, wo man zuerst sucht?
Ich habe trotzdem das Problem mit der lokalen Installation, da ein Bulk-Download aller Dateien nicht möglich ist ohne Desktop-Installation von GitHub.

**Comment by LeonAmtmann** [comment]
Entschuldigung, die Nutzerdokumentation wurde von mir extra ansehnlicher als die Wikieinträge gestaltet. An ein verlinken haben wir dann nicht mehr gedacht.
Wenn Sie om obersten Verzeichnis des Repositories sind, können Sie oben Rechts im Dropdown "Code" das gesamte Wiki als ZIP herunterladen.

**Comment by LeonAmtmann** [comment]
<img width="1172" alt="168154865-fa3051d7-4f45-4fb5-9b52-446f1aabed65 2" src="https://user-images.githubusercontent.com/35031775/168159069-9772d747-a003-4051-bc65-e555ddabaeea.png">
