### ISSUE TITLE
SRS: Datenmodell für Kabel nicht vorhanden

### ISSUE THREAD

**Issue by mrentsch65** [fabianthome/TINF20C_Team2_ModellingWizardForCables#5]
Sollte im SRS Kapitel 5 als Serie von Anforderungen /LDxx/ grob beschrieben sein, im SAS dann ausdetailliert als formale Spezifikation (z.B. XML-Schema).

**Comment by fabianthome** [comment]
Auf Grund der bevorstehenden Klausuren diese Woche, werden wir leider erst am kommenden Freitag anfangen können daran zu arbeiten.
