### ISSUE TITLE
Warum gibt es noch keine Testversion auf GitHub?

### ISSUE THREAD

**Issue by mrentsch65** [fabianthome/TINF20C_Team2_ModellingWizardForCables#8]
![image](https://user-images.githubusercontent.com/50681355/163756095-9bb7f796-f715-4d13-aa61-5120e1852922.png)

**Comment by LeonAmtmann** [comment]
Testversion ist unter EXECUTABLE/CableWizard/CableWizardBackend.txt
*exec name subject to change
